test_path=libs/numeric/ublas/test

BOOST_ROOT=$(HOME)/projects/svn/boost-trunk
CXXFLAGS=-Wall -ansi -pedantic -O0 -g -I. -I$(BOOST_ROOT)

all: $(test_path)/test_ticket7296

clean:
	rm -f $(test_path)/test_ticket7296 $(test_path)/test_ticket7296.o
